### ISSUE TITLE
Integration of EVIDEN's GraphCast

### ISSUE THREAD

**Issue by colon3ltocard** [meteofrance/py4cast#4]
* Wait for #2 and @cbovalo greenlight
* Write Settings class
* Write Torch nn.Module subclass
* Add model to CI/CD

**Comment by cbovalo** [comment]
@colon3ltocard it's up to you :)

**Comment by A669015** [comment]
The EVIDEN version of Graphcast is now available at https://github.com/AI4SIM/meteo_france

**Comment by colon3ltocard** [comment]
Will be done in mfai, closing this.
