### ISSUE TITLE
OOM on test set with PSDs

### ISSUE THREAD

**Issue by colon3ltocard** [meteofrance/py4cast#7]
We have a OOM error when running the test script on the full titan dataset.

**runai python_gpu bin/test.py /scratch/shared/py4cast/logs/comparison/titan/unetrpp/guib_unetrpp8512_0/epoch=69-val_mean_loss=17.30.ckpt --num_pred_steps 12**

Workaround: subsample and take one third of the test set

**Comment by flyIchtus** [comment]
Observations and fix :

- GPU memory is drifting slowly (30-100 mBytes added per test iteration), causing OOM on large test datasets
- ablating metrics does not stop the drift
- ablating plotters does stop the drift
- issue is in the plotter's `update` function, where the data is not transferred to CPU and accumulated along epoch
- adding `.cpu()` before accumulating stops the drift
- long run ongoing to check behaviour
