### ISSUE TITLE
Impossible to pip install onnxruntime > 1.16.3 on belenos

### ISSUE THREAD

**Issue by A669015** [meteofrance/py4cast#89]
On the MF belenos machine the `pip install onnxruntime==1.18.0` fails with the following error:
```
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.18.0 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime==1.18.0
```

Note it is possible to install this version using conda.

**Comment by A669015** [comment]
After investigation, it appears belenos is currently hosting a RHEL7.9 OS, with a GLIBC2.27, and since the version 1.17 onnxruntime only support GLIBC >= 2.28
![image](https://github.com/user-attachments/assets/12277879-c870-49c9-9a84-52018436136f)

Pip seems to detect the conflict, but is not able to resolve it.
On the other hand, conda doen't use the same onnxruntime packages, while it publishes its own packages. The conda onnxruntime libs are statically linked (in contrary to the pypi ones) and that seems to solve the issue (maybe they compile in their own for a glibc 2.27, and/or they embed many stuff that solves the issue ...)

**Comment by A669015** [comment]
While this limitation is related to a quite old OS version, I propose to document this situation in a **Known issues** section of the README. The move of the onnxruntime requirement from the `requirements.txt` to the `env.yaml` file could be documented as the preconized workaround.

**Comment by colon3ltocard** [comment]
Sounds good @A669015 !
